### ISSUE TITLE
Support for Canon XF 605?

### ISSUE THREAD

**Issue by OvrilPT** [bitfocus/companion-module-canon-xf#1]
Currently I'm not being able to connect my Canon XF 605 to the module in companion.
Don't know if there are significant changes between the XF 705 to make this not work.

Is there any chance I'm doing something wrong? Activating the camera remote connection in my camera, accessing with the IP, confirm I'm using the right port (80). Normal browser remote works, only getting error connecting through companion.

Thanks for the help

**Comment by josephdadams** [comment]
I made this work for the 705 (what I have) by reverse engineering the web browser remote. The 605 is too different to work with it. I’m available for hire to reverse engineer your 605 and make it work if you like. My email is on my github profile.

**Comment by josephdadams** [comment]
The 605 is supported via the canon-ptz module
